// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type InputPost struct {
	Title  string `json:"title"`
	Text   string `json:"text"`
	UserID int    `json:"userId"`
}

type InputUser struct {
	Name     string `json:"name"`
	Lastname string `json:"lastname"`
}
